name: CICD

on: workflow_dispatch

jobs:

  code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        run: echo "Code cloned"

  build:
    needs: code
    runs-on: ubuntu-latest

    steps:
      - name: Build container
        run: echo "Docker build completed"

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Test container
        run: echo "Tests passed"

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Deploy application
        run: echo "Application deployed"
